#RequireAdmin
Run( "\\achebr\gru\Software(GRU)\SAP BPC\EPM_Add-in_x64.exe")
If WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "This setup will perform an upgrade of 'EPM add-in for Microsoft Office'. Do you want to continue?", 10) Then
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Resuming the InstallShield Wizard for EPM add-in for Microsoft Office")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The InstallShield Wizard has successfully installed EPM add-in for Microsoft Office. Click Finish to exit the wizard.")
    Send("{ENTER}")
    Sleep(2500)
    Run( "D:\testes_para\sap\EPM_Add-in_x64.exe" )
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The InstallShield(R) Wizard will allow you to modify, repair, or remove EPM add-in for Microsoft Office. To continue, click Next.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Repair installation errors in the program. This option fixes missing or corrupt files, shortcuts, and registry entries.")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Repair installation errors in the program. This option fixes missing or corrupt files, shortcuts, and registry entries.", "Button4")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Repair installation errors in the program. This option fixes missing or corrupt files, shortcuts, and registry entries.", "Button6")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "You have chosen to remove the program from your system.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The InstallShield Wizard has successfully uninstalled EPM add-in for Microsoft Office. Click Finish to exit the wizard.")
    Send("{ENTER}")
    Sleep(2500)
    Run( "D:\testes_para\sap\EPM_Add-in_x64.exe" )
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "WARNING: This program is protected by copyright law and international treaties.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.", "Button3")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.")
    ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information", "RichEdit20W1", "user")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "RichEdit20W2")
    Send("Ache")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "Button2")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button7")
    ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Edit1", "Portuguese")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button1")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The EPM add-in starts with Office")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button4")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button5")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button6")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button7")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button1")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Click Next to install to this folder, or click Change to install to a different folder.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "If you want to review or change any of your installation settings, click Back. Click Cancel to exit the wizard.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The InstallShield Wizard has successfully installed EPM add-in for Microsoft Office. Click Finish to exit the wizard.")
    Send("{ENTER}")
    exit
EndIf

If WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "WARNING: This program is protected by copyright law and international treaties.") Then
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.", "Button3")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.")
    ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information", "RichEdit20W1", "user")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "RichEdit20W2")
    Send("Ache")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "Button2")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button7")
    ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Edit1", "Portuguese")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button1")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The EPM add-in starts with Office")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button4")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button5")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button6")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button7")
    ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button1")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Click Next to install to this folder, or click Change to install to a different folder.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "If you want to review or change any of your installation settings, click Back. Click Cancel to exit the wizard.")
    Send("{ENTER}")
    WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The InstallShield Wizard has successfully installed EPM add-in for Microsoft Office. Click Finish to exit the wizard.")
    Send("{ENTER}")
    exit
EndIf