#RequireAdmin
Run( "D:\testes_para\sap\EPM_Add-in_x64.exe" )
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "WARNING: This program is protected by copyright law and international treaties.")
Send("{ENTER}")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please read the following license agreement carefully.", "Button3")
Send("{ENTER}")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.")
ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information", "RichEdit20W1", "user")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "RichEdit20W2")
Send("Ache")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "Button2")
Send("{ENTER}")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button7")
ControlSetText("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Edit1", "Portuguese")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Select the application language:", "Button1")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "The EPM add-in starts with Office")
Send("{ENTER}")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button4")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button5")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button6")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button7")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Create shortcuts in the Windows Start Menu", "Button1")
WinWaitActive("EPM add-in for Microsoft Office - InstallShield Wizard", "Click Next to install to this folder, or click Change to install to a different folder.")
Send("{ENTER}")