#RequireAdmin
Run("D:\testes_para\sap\IBP_Add-in_NET6_x64 2308.exe")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "WARNING: This program is protected by copyright law and international treaties.")
Send("{ENTER}")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard","Please enter your information.")
ControlClick("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Please enter your information.", "RichEdit20W1")
ControlSetText("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Please enter your information", "RichEdit20W1", "user")
ControlClick("EPM add-in for Microsoft Office - InstallShield Wizard", "Please enter your information.", "RichEdit20W2")
Send("Ache")
ControlClick("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Please enter your information.", "Button2")
ControlClick("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Please enter your information.", "Button5")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Choose the default application language")
Send("{ENTER}")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "Click Next to install to this folder, or click Change to install to a different folder.")
Send("{ENTER}")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "To learn more about disabling the Office Clipboard")
Send("{ENTER}")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "The wizard is ready to begin installation.")
Send("{ENTER}")
WinWaitActive("SAP IBP, add-in for Microsoft Excel - InstallShield Wizard", "The InstallShield Wizard has successfully installed SAP IBP, add-in for Microsoft Excel. Click Finish to exit the wizard.")
Send("{ENTER}")